import Head from "next/head";
import Image from "next/image";
import Layout from "../components/layout";
import Main from "../components/main/main";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>이선민 포트폴리오</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Main />
    </Layout>
  );
}
